### ISSUE TITLE
toGC changed to send in node-steam

### ISSUE THREAD

**Issue by zm3y** [DoctorMcKay/node-tf2#8]
Hello! After update node-steam to 1.0.0 this module stops work with "this._steam.toGC(440, type, body.flip().toBuffer());". Node-steam uses new "reworked semantics" with send/message.

**Comment by DoctorMcKay** [comment]
Yep, it'll be updated for node-steam 1.0.0 soon enough.

**Comment by zm3y** [comment]
I see you update to new steam, but something still not work. I start game by native user handler by 
steamUser.gamesPlayed({games_played: { "game_id": 440 }});
And I got error:
		if(appids.indexOf(440) != -1) {
		          ^
TypeError: undefined is not a function

**Comment by DoctorMcKay** [comment]
That should be fixed in d868b75 (2.0.1 on npm).
